use_frameworks!

platform :ios, '8.0'

target 'BDRecognize_Example' do
  pod 'BDRecognize', :path => '../'

  target 'BDRecognize_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
